Metrics app capstone
ahmed-al-farouq/Metrics-Webapp pull request #1
Opened 2021-11-18 13:09 UTC by ahmed-al-farouq

What I did:
- [ ] initialized the react app
- [ ] fetched continents and countries
- [ ] created navbar, home, and details page
- [ ] added styling
- [ ] created testing for fetching and components
- [ ] created readme file
- [ ] deployed the site
- [ ] created a loo video link below:
https://www.loom.com/share/b6ae686daccc4031a7be38e55885e10a

2021-11-18 14:19 UTC, rloterh requested changes
Hi Omar, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to complete this project but you are almost there! 🚦  🚦  

## Good Points 👍 
- App is correctly deployed
- Redux is effectively used to manage state data
- Test cases are passing
- No linter errors

## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 4 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-18 14:19 UTC, rloterh commented on README.md
> +
The video presentation showcasing your project is **incomplete**. Kindly endeavor to record a maximum of 5 minutes video presenting the features of the project. The video should:
- [ ]  contain a **clear and objective description** of the project in professional English. The topic and purpose of the project are made clear.
- [ ]  contain a demo of the project, **highlighting all the project features**.
- [ ]  contain a **highlight about a piece of the code** the student finds interesting or is proud of making.

2021-11-19 13:09 UTC, ahmed-al-farouq commented on README.md
> +
Thanks for the feedback sir.

2021-11-20 00:08 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @ahmed-al-farouq,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-20 00:19 UTC, merged